version: '3.8'
services:
  db:
    image: postgres
    container_name: crm-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist data
    ports:
      - "5433:5432"  # Expose PostgreSQL to the app
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"  # Expose pgAdmin on localhost:5050
    depends_on:
      - db  # Ensure pgAdmin starts after the database

volumes:
  postgres_data:
    driver: local  # Define a volume for persistent data

networks:
  crm-network:
    driver: bridge  # Use bridge network for internal communication
